# Generated by Django 6.0.5 on 2026-06-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('full_desc', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('features', models.JSONField(default=list, help_text='List of features')),
                ('why_choose_us', models.JSONField(blank=True, default=list, help_text='List of reasons to choose us')),
                ('conclusion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
